<?php

/**
 * Class GamesSeeder
 *
 */
class GamesSeeder extends Seeder {

    public function run()
    {
        $this->db->truncate('games');

        $this->db->insert_batch('games', [
            [
                'code' => 'ag',
                'start_code' => 'ag',
                'name' => 'Adrenaline Gamer',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'csgo',
                'start_code' => 'csgo',
                'name' => 'Counter-Strike: Global Offensive',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '740',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'cssource',
                'start_code' => 'cstrike',
                'name' => 'Counter-Strike: Source',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '232330',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'cssv34',
                'start_code' => 'cstrike',
                'name' => 'Counter-Strike: Source v34',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '/root/repository/cssv34',
                'remote_repository' => '',
            ],
            [
                'code' => 'cstrike',
                'start_code' => 'cstrike',
                'name' => 'Counter-Strike 1.6',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'czero',
                'start_code' => 'czero',
                'name' => 'Counter-Strike: Condition Zero',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '90 mod czero',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'dmc',
                'start_code' => 'dmc',
                'name' => 'Deathmatch Classic',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '90 mod dmc',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'dod',
                'start_code' => 'dod',
                'name' => 'Day of Defeat',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '90 mod dod',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'dods',
                'start_code' => 'dods',
                'name' => 'Day of Defeat: Source',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '232290',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'garrysmod',
                'start_code' => 'garrysmod',
                'name' => 'Garry\'s Mod',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '4020',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'gearbox',
                'start_code' => 'gearbox',
                'name' => 'Half-Life: Opposing Force',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '90 mod gearbox',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'hl2mp',
                'start_code' => 'hl2mp',
                'name' => 'Half-Life 2',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '232370',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'hurtworld',
                'start_code' => 'hurtworld',
                'name' => 'HurtWorld',
                'engine' => 'hurtworld',
                'engine_version' => '1',
                'app_id' => '405100',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'l4d',
                'start_code' => 'l4d',
                'name' => 'Left 4 Dead',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'l4d2',
                'start_code' => 'l4d2',
                'name' => 'Left 4 Dead 2',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '222860',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'minecraft',
                'start_code' => 'minecraft',
                'name' => 'Minecraft',
                'engine' => 'minecraft',
                'engine_version' => '1',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'mta',
                'start_code' => 'mta',
                'name' => 'GTA: Multi Theft Auto',
                'engine' => 'mta',
                'engine_version' => '1',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'ns',
                'start_code' => 'ns',
                'name' => 'Natural Selection',
                'engine' => 'goldsource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'ricochet',
                'start_code' => 'ricochet',
                'name' => 'Ricochet',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '90 mod ricochet',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'rust',
                'start_code' => 'rust',
                'name' => 'Rust Legacy',
                'engine' => 'rust',
                'engine_version' => 'legacy',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'rust_exp',
                'start_code' => 'rust_exp',
                'name' => 'Rust Experimental',
                'engine' => 'rust',
                'engine_version' => 'experimental',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'samp',
                'start_code' => 'samp',
                'name' => 'GTA: San-Andreas Multiplayer',
                'engine' => 'samp',
                'engine_version' => '1',
                'app_id' => '0',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'svencoop',
                'start_code' => 'svencoop',
                'name' => 'Sven Co-op',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'tf2',
                'start_code' => 'tf',
                'name' => 'Team Fortress 2',
                'engine' => 'Source',
                'engine_version' => '1',
                'app_id' => '232250',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'tfc',
                'start_code' => 'tfc',
                'name' => 'Team Fortress Classic',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '90 mod tfc',
                'local_repository' => '',
                'remote_repository' => '',
            ],
            [
                'code' => 'valve',
                'start_code' => 'valve',
                'name' => 'Half-Life 1',
                'engine' => 'GoldSource',
                'engine_version' => '1',
                'app_id' => '90',
                'app_set_config' => '',
                'local_repository' => '',
                'remote_repository' => '',
            ],
        ]);
    }
}
